### ISSUE TITLE
Queuing Service for Background Tasks

### ISSUE THREAD

**Issue by mattgi** [Kodemon/reach-api#14]
It is important to only block a user for tasks that a response relies upon. For other tasks, they should be taken out of the current request lifecycle and processed as background tasks.

A queuing solution allows this to occur nicely.

What is implemented should include functionality to retry failed jobs and also schedule jobs to occur in the future. Priority jobs and delays should also be available.

A solution that works nicely in Express is Kue:
https://github.com/Automattic/kue
https://github.com/lykmapipo/kue-scheduler

**Comment by Kodemon** [comment]
Yeah this will be a priority feature, I looked at kue and it seems to be node so I should be able to create a kue service for reach.

**Comment by Kodemon** [comment]
@mattgi Latest version extends kue

Have a look at:
https://github.com/Kodemon/reach-api/blob/dev/lib/reach/kue.js
https://github.com/Kodemon/reach-api/blob/dev/api/config/default.js#L66

I was thinking of creating a folder `./api/tasks` where you can register your job queues that are all run on bootstrap.

As a bonus I can also automatically start the kue interface once I have bootstrapped all the jobs so you even get that working on a configuration port. I just need to find a good authentication solution for that.

Can I get your input on this?

**Comment by mattgi** [comment]
in my projects I create a job-service to define Kue and set things up.. under that I include a handlers folder which is looped through similar to what you are thinking..

**Comment by Kodemon** [comment]
@mattgi Queue is now a service that loads jobs in the same manner as bootstrap loads services and modules. This way you can easily change the implementation of queuing in the API.
