### ISSUE TITLE
Data Migrations

### ISSUE THREAD

**Issue by mattgi** [Kodemon/reach-api#7]
- When adding a module a consumer may wish to include some seed data (e.g. admin/user roles).
- When a schema changes, a strategy needs to exist to migrate data (e.g. how does one manage the move to merge firstName and lastName fields in to a single name field).

An implementation for data migrations could occur out of process (separate CLI) however it needs to be able to make use of the models defined in the app.

**Comment by Kodemon** [comment]
Yes this is definitely a must have for any decent API, data migration is something I will definitely take a serious look at and possibly give a shout out to for help as its not my strongest suit.

**Comment by mattgi** [comment]
south is a good example for relational dbs @ https://south.readthedocs.org/en/latest/

**Comment by Kodemon** [comment]
This is one of the bigger undertakings when it comes to features, once the model's are properly locked down we can start thinking about how to best approach this issue.

**Comment by Kodemon** [comment]
@mattgi I am placing this in the icebox for now, its a pretty expansive feature and would most certainly be a service implementation. This will not be a requirement for beta api release though.

This will be re-opened when its time to set this up. Feel free to add ideas and comments to this issue.
