### ISSUE TITLE
Document a Contrib Strategy

### ISSUE THREAD

**Issue by mattgi** [Kodemon/reach-api#8]
If someone wishes to contribute modules to reach, there needs to be a controlled way to do so. i.e. do you intend on allowing PRs and pulling in anything and everything... or maybe a contribs repo where people can add their own modules. Just thinking that say I want to add payment and notification modules, how do I share them?

**Comment by Kodemon** [comment]
I have been working on a CLI interface for reach where I was thinking of how to manage modules, the idea is to have no modules in this repository as a default when we move to the master branch then have a central host for modules where you can install using `reach install module-name`.

I had a working version of this going but consider the amount of work I put this on ice until the API is mature enough in other areas before working on module management.

**Comment by Kodemon** [comment]
First implementation of [reach-cli](https://www.npmjs.com/package/reach-cli) is up on NPM.

Edit your api `package.json` and add `reach` settings

```json
"reach": {
  "modules": [
    "http://localhost:3000"
  ]
}
```

The `reach.modules` array should point to root locations of `module.zip` files
